mi_sitio/comments/urls.py
from django.urls import path
from . import views


app_name = 'comments'
urlpatterns = [
    path('/add',views.add, name='add'),    
    path('',views.listado, name='listado'),
    path('/actualizar/<int:id_comentario>', views.actualizar, name='actualizar'),
    path('/eliminar/<int:id_comentario>', views.eliminar, name='eliminar'),
]

mi_sitio/elements/urls.py
from django.urls import path
from .views import home_page_view

urlpatterns = [
    path('home', home_page_view, name='home'),    
]

mi_sitio/mi_sitio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', include('elements.urls')),
    path('tareas', include('comments.urls'))
]

mi_sitio/comments/models.py
from django.db import models
from elements.models import Elemento

# Create your models here.
class Comentario(models.Model):
    texto = models.TextField(max_length=250)
    fecha_posted = models.DateTimeField(auto_now_add=True)
    element = models.ForeignKey(Elemento, on_delete=models.CASCADE, null=True)    

    def __str__(self):
        return 'Commentario #{}'.format(self.id)

mi_sitio/elements/models.py
from django.db import models
from django.contrib import admin
from django.core.exceptions import ValidationError

# Create your models here.

class Categoria(models.Model):
    titulo = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)

    def __str__(self):
        return self.titulo
    
class Tipo(models.Model):
    titulo = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)

    def __str__(self):
        return self.titulo
    
class Elemento(models.Model):
    titulo = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255,blank=True)
    descripcion = models.TextField()
    precio = models.DecimalField(max_digits=10, decimal_places=2,default=6.10)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    tipo = models.ForeignKey(Tipo, on_delete=models.CASCADE)
    creado=models.DateTimeField(auto_now_add=True)
    actualizado=models.DateTimeField(auto_now=True)

    #personalizacion 2
    #@admin.display(description='¿Barato?')
    @admin.display(boolean=True, description='¿Barato?')
    def cheap(self):
        return 0 <= self.precio < 9.9

    def __str__(self):
        return self.titulo
    
    #Validaciones personalizadas
    def clean(self):
        if self.precio < 0:
            raise ValidationError('El precio no puede ser negativo.')

mi_sitio/comments/forms.py
from django.forms import ModelForm
from .models import Comentario

class ComentarioForm(ModelForm):
    class Meta:
        model = Comentario
        fields = ['texto']

mi_sitio/comments/views.py
from django.shortcuts import render,redirect, get_object_or_404, get_list_or_404
from django.core.paginator import Paginator
from django.http import Http404
from .models import Comentario
from .forms import ComentarioForm
# Create your views here.
""" def add(request):
    if(request.method == 'POST'):
        #save
        if request.POST.get('texto') != '' :            
            comentario=Comentario()
            comentario.texto=request.POST.get('texto')
            comentario.save()
        else:
            print("No hay texto")
    if(request.method=='GET'):
        pass
    return render(request, 'add.html') """
#insertar un comentario
def add(request):
    if(request.method == 'POST'):
        formulario=ComentarioForm(request.POST)
        comentario=formulario.save()
        print("Comentario guardado: ", comentario)
        return redirect('comments:listado')
    else:
        formulario=ComentarioForm()
    return render(request, 'comentarios/add.html', {'formulario': formulario})

#listar los comentarios
def listado(request):
    #listado=get_list_or_404(Comentario) #es para verificar si el listado esta vacio
    listado=Comentario.objects.all()
    #adicionamops la paginacion
    paginator=Paginator(listado, 3) #3 comentarios por pagina
    page_number=request.GET.get('page')
    comentarios_page=paginator.get_page(page_number)

    return render(request, 'comentarios/listado.html', {'listado': comentarios_page})

#actualizar un comentario
def actualizar(request, id_comentario):
    
    #metodo con get_object_or_404
    comentario=get_object_or_404(Comentario, id=id_comentario)
    #metodo con manejo de excepciones
    #try:
    #    comentario=get_object_or_404(Comentario, id=id_comentario)
    #except Http404:
    #    raise Http404("Comentario no encontrado")
    
    
    #metodo alternativo
    #try:
    #    comentario=Comentario.objects.get(id=id_comentario)
    #except Comentario.DoesNotExist:
    #    raise Http404("Comentario no encontrado")
    
    if(request.method == 'POST'):
        formulario=ComentarioForm(request.POST, instance=comentario)
        if formulario.is_valid():
            comentario=formulario.save()
            print("Comentario actualizado: ", comentario)
            return redirect('comments:listado')
    else:
        formulario=ComentarioForm(instance=comentario)
    return render(request, 'comentarios/add.html', {'formulario': formulario})

#eliminar un comentario
def eliminar(request, id_comentario):
    #comentario=Comentario.objects.get(id=id_comentario)
    comentario=get_object_or_404(Comentario, id=id_comentario)
    if request.method=='POST':
        comentario.delete()
        return redirect('comments:listado')
    #listado=Comentario.objects.all()    
    #return render(request, 'comentarios/listado.html', {'listado': listado})

mi_sitio/elements/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.

def home_page_view(request):
    return HttpResponse("Welcome to the Home Page of Elements App!")

mi_sitio/comments/templates/comentarios/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Página para agregar</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maiores sed, facilis velit esse sequi repudiandae ratione, blanditiis unde eveniet quas rem dolorum? Exercitationem ducimus cupiditate totam in, voluptatum rem quasi!</p>
{% comment %} <form action="add" method="post">
    
    <label for="">Texto:</label>
    <textarea required name="texto"></textarea>
    {% csrf_token %}
    <input type="submit" value="Enviar">
</form> {% endcomment %}

<form action="" method="post">
    
    {{ formulario.as_p }}   
     {{ formulario.text }} 
    {% csrf_token %}
    <!--input type="submit" value="Enviar"-->
    <button type="submit">Enviar</button>
    <button type="submit" ><a href="{% url 'comments:listado' %}">Retornar</a></button>
</form>
</body>
</html>

mi_sitio/comments/templates/comentarios/listado.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<a href="{% url 'comments:add' %}" target="_blank">Crear</a>
    <h1>Listado de Comentarios</h1>
    <ul>
        {% for comentario in listado %}
            <li>{{ comentario.texto }}: {{ comentario.fecha_posted }} 
            <!--a href="/tareas/actualizar/{{ comentario.id }}">Editar</a-->
                 -- <a href="{% url 'comments:actualizar'  comentario.id %}">Editar</a>/
                 
                 <form action="{% url 'comments:eliminar'  comentario.id %}" method="post" style="display:inline;">
                    {% csrf_token %}
                <input type="submit" value="Eliminar"></button>     
                </form>              
                    
                
            </li>
        {% empty %}
            <li>No hay comentarios disponibles.</li>
        {% endfor %}
         </ul>
        <nav>
            <ul class="pagination justify-content-center">
                {% if listado.has_previous %}
                    <li class="page-item"><a  class="page-link" href="?page={{ listado.previous_page_number }}">⬅️</a></li>
                {% endif %}
                    <li>             
                        {% for num in listado.paginator.page_range %}
                            {% if listado.number == num %}
                                <a href="?page={{ num }}" class="page-link activate"><strong>{{ num }}</strong></a>
                            {% else %}
                                <a href="?page={{ num }}"  class="page-link">{{ num }}</a>
                            {% endif %}
                        {% endfor %}
                    </li>
                {% if listado.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ listado.next_page_number }}">➡️</a></li>
                {% endif %}
            </ul>
        </nav>
        Página {{ listado.number }} de {{ listado.paginator.num_pages }} 
   
</body>
</html>